spring:
  application:
    name: department-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    info:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
