spring:
  application:
    name: department-microservice

  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# =========================
# Resilience4j Configuration
# =========================
resilience4j:
  circuitbreaker:
    instances:
      departmentCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms

  ratelimiter:
    instances:
      departmentRateLimiter:
        limit-for-period: 10
        limit-refresh-period: 1s

# =========================
# Actuator / Monitoring
# =========================
management:
  endpoints:
    web:
      exposure:
        include: "*"   # inclut info, health, prometheus, etc.

  endpoint:
    info:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

# =========================
# Logging
# =========================
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
