spring:
  application:
    name: student-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/students_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    non-secure-port: ${server.port}   
    instance-id: ${spring.application.name}:${random.value}

resilience4j:
  retry:
    instances:
      studentRetry:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  
  ratelimiter:
    instances:
      studentRateLimiter:
        limit-for-period: 5        # Réduit à 5 pour tester
        limit-refresh-period: 1s   #  1 seconde
        timeout-duration: 0        # Pas d'attente, rejette immédiatement
  
  circuitbreaker:
    instances:
      studentCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.lang.RuntimeException
  
  timelimiter:
    instances:
      studentTimeLimiter:
        timeout-duration: 3s

#  Configuration Actuator et Prometheus
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    io.github.resilience4j: DEBUG
